# version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: secure_vault_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=secure_vault
    # ports: 
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  migrate:
    build: .
    command: npx prisma migrate deploy
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/secure_vault
    
    

  app:
    build: .
    env_file:
      - .env
    container_name: secure_vault_app
    restart: always
    ports: 
      - "${PORT}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/secure_vault    
    depends_on:
      - db

volumes: 
  postgres_data:
